import { sql } from 'drizzle-orm'
import { getTableConfig } from 'drizzle-orm/pg-core'
import type { PgTable } from 'drizzle-orm/pg-core/table'
import {
  aesyncCheckpoint,
  aesyncContractState,
  aesyncMeta,
} from '../schema/internal.js'
import type { DrizzleInstance } from './types.js'

function extractSqlString(chunks: unknown[]): string {
  const parts: string[] = []
  for (const chunk of chunks) {
    if (
      chunk &&
      typeof chunk === 'object' &&
      'value' in chunk &&
      Array.isArray((chunk as { value: unknown }).value)
    ) {
      parts.push(...(chunk as { value: string[] }).value)
    }
  }
  return parts.join('')
}

function columnDefault(col: {
  hasDefault: boolean
  default: unknown
  defaultFn: unknown
  generatedIdentity: unknown
}): string {
  if (col.generatedIdentity) return ''
  if (!col.hasDefault) return ''
  if (col.defaultFn) return ''
  const d = col.default
  if (d === undefined || d === null) return ''
  if (typeof d === 'object' && d !== null && 'queryChunks' in d) {
    const sqlStr = extractSqlString(
      (d as { queryChunks: unknown[] }).queryChunks,
    )
    return sqlStr ? ` DEFAULT ${sqlStr}` : ''
  }
  if (typeof d === 'string') return ` DEFAULT '${d}'`
  if (typeof d === 'number' || typeof d === 'boolean')
    return ` DEFAULT ${String(d)}`
  return ''
}

function buildCreateTable(table: PgTable): string {
  const config = getTableConfig(table)
  const colDefs: string[] = []

  for (const col of config.columns) {
    let def = `"${col.name}" `

    if (col.generatedIdentity) {
      def += 'BIGINT GENERATED BY DEFAULT AS IDENTITY'
    } else {
      def += col.getSQLType()
    }

    if (col.primary && config.primaryKeys.length === 0) {
      def += ' PRIMARY KEY'
    }
    if (col.notNull && !col.primary) {
      def += ' NOT NULL'
    }
    def += columnDefault(col)
    colDefs.push(def)
  }

  if (config.primaryKeys.length > 0) {
    for (const pk of config.primaryKeys) {
      const cols = pk.columns.map((c) => `"${c.name}"`).join(', ')
      const name = pk.getName()
      colDefs.push(`CONSTRAINT "${name}" PRIMARY KEY (${cols})`)
    }
  }

  const schema = config.schema ? `"${config.schema}".` : ''
  return `CREATE TABLE IF NOT EXISTS ${schema}"${config.name}" (\n  ${colDefs.join(',\n  ')}\n)`
}

function buildCreateIndexes(table: PgTable): string[] {
  const config = getTableConfig(table)
  const stmts: string[] = []

  for (const idx of config.indexes) {
    const unique = idx.config.unique ? 'UNIQUE ' : ''
    const colNames: string[] = []
    for (const col of idx.config.columns) {
      if (col && 'name' in col && typeof col.name === 'string') {
        colNames.push(`"${col.name}"`)
      }
    }
    if (colNames.length === 0) continue
    const name = idx.config.name ?? `${config.name}_${colNames.join('_')}_idx`
    const schema = config.schema ? `"${config.schema}".` : ''
    stmts.push(
      `CREATE ${unique}INDEX IF NOT EXISTS "${name}" ON ${schema}"${config.name}" (${colNames.join(', ')})`,
    )
  }

  return stmts
}

export async function applyInternalMigrations(
  qb: DrizzleInstance,
): Promise<void> {
  const internalTables: PgTable[] = [
    aesyncMeta,
    aesyncContractState,
    aesyncCheckpoint,
  ]
  for (const table of internalTables) {
    const ddl = buildCreateTable(table)
    await qb.execute(sql.raw(ddl))

    const indexes = buildCreateIndexes(table)
    for (const idx of indexes) {
      await qb.execute(sql.raw(idx))
    }
  }
}

export async function applyMigrations(
  qb: DrizzleInstance,
  tables: Record<string, PgTable>,
): Promise<void> {
  for (const table of Object.values(tables)) {
    const ddl = buildCreateTable(table)
    await qb.execute(sql.raw(ddl))

    const indexes = buildCreateIndexes(table)
    for (const idx of indexes) {
      await qb.execute(sql.raw(idx))
    }
  }
}
