// Auto-generated by @growae/aesync — do not edit

declare module 'aesync:registry' {
  interface AeSyncRegistry {
    fns: Array<{ name: string; fn: (...args: any[]) => Promise<void> }>
    _api_routes: Array<{
      method: string
      path: string
      handler: (...args: any[]) => any
    }>
    _api_middleware: Array<(...args: any[]) => any>
    on(
      name:
        | 'ct_25cqTw85wkF5cbcozmHHUCuybnfH9WaRZXSgEcNNXG9LsCJWTN:CreateCommunity'
        | 'ct_25cqTw85wkF5cbcozmHHUCuybnfH9WaRZXSgEcNNXG9LsCJWTN:CreateCollection'
        | 'BclTokenSale:Buy'
        | 'BclTokenSale:Sell'
        | 'BclTokenSale:PriceChange',
      fn: (...args: any[]) => Promise<void>,
    ): void
    get(path: string, handler: (...args: any[]) => any): void
    post(path: string, handler: (...args: any[]) => any): void
    use(handler: (...args: any[]) => any): void
  }
  export const aesync: AeSyncRegistry
}

declare module 'aesync:schema' {
  export * from './schema.js'
}

declare module 'aesync:api' {
  export let db: any
  export let client: any
  export function setDb(d: any): void
  export function setClient(c: any): void
}
